{
    "creators": [
        {
            "orcid": "0000-0003-0419-4546",
            "name": "Raphael Quast",
            "affiliation": "TU Wien Department of Geodesy and Geoinformation"
        }
    ]
}
